<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

        <!-- NuGet Package Details -->
        <PackageId>NOBS.JobSystem.UI</PackageId>
        <Version>1.0.1</Version>
        <Authors>Scippo97</Authors>
        <Company>Scippo97 Sensible Productions</Company>
        <Description>A Blazor-based monitoring UI for the NOBS.JobSystem library.</Description>
        <PackageTags>job;scheduler;cron;background;worker;dotnet;blazor;ui</PackageTags>
        <PackageProjectUrl>https://github.com/scippo97sensibleproductions/NOBS.JobSystem</PackageProjectUrl>
        <RepositoryUrl>https://github.com/scippo97sensibleproductions/NOBS.JobSystem.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>

        <!-- SourceLink Configuration -->
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\" />
        <None Include="../LICENSE" Pack="true" PackagePath="\" />
        <None Include="../icon.png" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NOBS.JobSystem\NOBS.JobSystem.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    </ItemGroup>

</Project>